services:
  minio-console:
    image: minio/minio:latest
    container_name: minio-console
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_SERVER_URL: "${MINIO_SERVER_URL}"
      MINIO_BROWSER_REDIRECT_URL: "https://console.chrry.dev"
    networks:
      - minio-network
    labels:
      - "coolify.managed=true"
      - "coolify.type=service"
      - "coolify.name=minio-console"
      - "traefik.enable=true"
      - "traefik.http.routers.minio-console.rule=Host(`console.chrry.dev`)"
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-console.tls=true"
      - "traefik.http.routers.minio-console.tls.certresolver=letsencrypt"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"

networks:
  minio-network:
    external: true